# .github/workflows/deploy.yml

name: "Terraform Deploy to Azure"

on:
  push:
    branches:
    #   - dev
      - feature/terraform-ci
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout repo
        uses: actions/checkout@v3

      - name: ğŸ”§ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6 # ou ta version prÃ©fÃ©rÃ©e

      - name: ğŸ” Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    # La partie network :
      - name: ğŸ“¦ Terraform Init
        run: terraform init
        working-directory: infra/terraform/network

      - name: âœ… Terraform Validate
        run: terraform validate
        working-directory: infra/terraform/network

      - name: ğŸ“ Terraform Format
        run: terraform fmt -check
        working-directory: infra/terraform/network

      - name: ğŸ“„ Terraform Plan
        run: terraform plan -out=tfplan-network
        working-directory: infra/terraform/network
    
        # La partie vm-linux  :
      - name: ğŸ“¦ Terraform Init
        run: terraform init
        working-directory: terraform/vm-linux

      - name: âœ… Terraform Validate
        run: terraform validate
        working-directory: terraform/vm-linux

      - name: ğŸ“ Terraform Format
        run: terraform fmt -check
        working-directory: terraform/vm-linux

      - name: ğŸ“„ Terraform Plan
        run: terraform plan -out=tfplan-vmlinux
        working-directory: terraform/vm-linux

    #   - name: ğŸš€ Terraform Apply
    #     if: github.ref == 'refs/heads/main'
    #     run: terraform apply -auto-approve tfplan